### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by RMCoder198** [fossasia/jobs.fossasia.org#2]
Search bar should be on top .

**Comment by RMCoder198** [comment]
I am working on it.

**Comment by heysadboy** [comment]
@RMCoder198 Please also attach screenshots when you open an issue if possible.

**Comment by RMCoder198** [comment]
This repo contains only one html file and i can't change search bar position using that html file .
If anyone can help me to solve this issue please help.

**Comment by mariobehling** [comment]
This repo is a simple forward and does not require any work. Would be great if you help in a coding project. The websites don't need that much attention.
